media: 
  input: public
  output: /
content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    fields:
      - name: title
        label: Titre
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Contenu
        type: rich-text