media: 
  input: public
  output: /
content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename:
      template: "{primary}.md"
    fields:
      - name: title
        label: Titre
        type: string
        options:
          maxlength: 70
      - name: description
        label: Description
        type: text
        options:
          maxlength: 140
      - name: body
        label: Contenu
        type: rich-text
      - name: formation
        label: Page formation
        description: Si actif, la liste des formations du CEFI Solidaires Bretagne sera ajoutée sur la page sous le contenu.
        type: boolean
        default: false
      - name: map
        label: Carte
        description: Permet d'afficher et de personnaliser une carte sur la page. Laisser vide pour ne pas afficher de carte.
        type: object
        fields:
          - name: latitude
            label: Latitude
            type: number
          - name: longitude
            label: Longitude
            type: number
          - name: address
            label: Adresse affichée
            type: string
          - name: transit
            label: Accès en métro
            type: string
          - name: link
            label: Lien GPS
            # pattern:
            #   regex: "^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,63}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$"
            #   message: "Veuillez entrer une URL valide"
            type: string