media: 
  input: public
  output: /
content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename:
      template: "{primary}.md"
      field: create
    fields:
      - name: title
        label: Titre
        type: string
        options:
          maxlength: 70
      - name: description
        label: Description
        type: text
        options:
          maxlength: 140
      - name: body
        label: Contenu
        type: rich-text